theme: jekyll-theme-hacker
title: Saurav Bajracharya
description: Hi I am Saurav Bajracharya, a Full Stack Software Engineer with a specialization in Frontend Development
github:
  profile_url: https://github.com/sauravbajra
