# config.yml

# backend:
#   name: git-gateway
#   branch: main # Branch to update (optional; defaults to master)
backend:
  name: github
  branch: main
  repo: "sauravbajra/sauravbajra.github.io"
  base_url: https://decap.mydomain.com
media_folder: 'assets/uploads'
collections:
  - name: 'blog'
    label: 'Blog'
    folder: '_posts/'
    fields:
      - { name: Title }
